#retrieve all weather observable properties in our vocabulary

PREFIX weo: <http://ns.inria.fr/meteo/ontology/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

select * where {
  ?x  a  weo:WeatherProperty; skos:prefLabel ?l .
}


