#calculate average wind speed at each station during the first week of august of 2021

PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX wep: <http://ns.inria.fr/meteo/ontology/property/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX weo: <http://ns.inria.fr/meteo/ontology/>

select ?jour ?stationID  ?n (avg(?v) as ?avg_speed_wind)
FROM <http://ns.inria.fr/meteo/observation/2021> 
FROM <http://ns.inria.fr/meteo/weatherstation>
 where {
  ?obs a  <http://ns.inria.fr/meteo/ontology/MeteorologicalObservation>; 
sosa:observedProperty
  <http://ns.inria.fr/meteo/vocab/weatherproperty/windAverageSpeed>  ;
sosa:hasSimpleResult ?v; 
wep:madeByStation ?station ;
sosa:resultTime ?t .
BIND (xsd:date(?t) AS ?jour) 
FILTER(?jour>= xsd:date("2021-08-01"))
FILTER(?jour<= xsd:date("2021-08-07"))
?station rdfs:label ?n ; weo:stationID ?stationID
}
GROUP BY ?stationID ?n ?jour
ORDER BY ?n ?jour
