#lists weather properties labels, abbreviations and their possible units 
prefix qudt: <http://qudt.org/schema/qudt/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix weo: <http://ns.inria.fr/meteo/ontology/> 
prefix wep: <http://ns.inria.fr/meteo/ontology/property/> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select * where {
  ?x a weo:WeatherProperty; skos:prefLabel ?l.
  OPTIONAL {?x qudt:applicableUnit ?u}
  OPTIONAL {?x wep:applicableWMOcode  ?u}
}

